export const LEARNING_CREATE_COURSE_ACTIVE_STEP = "CREATE_LEARNING_COURSE_NAVIGATION";
export const LEARNING_CREATE_COURSE_STEP_VALIDITY = "LEARNING_CREATE_COURSE_STEP_VALIDITY";
export const LEARNING_CREATE_COURSE_FILL_FORM_FIELD = "LEARNING_CREATE_COURSE_FILL_FORM_FIELD";
export const LEARNING_CREATE_COURSE_NEXT_STEP_REQUEST = "LEARNING_CREATE_COURSE_NEXT_STEP_REQUEST";
export const LEARNING_CREATE_COURSE_FINAL_CREATE_REQUEST = "LEARNING_CREATE_COURSE_FINAL_CREATE_REQUEST";
export const LEARNING_CREATE_COURSE = "LEARNING_CREATE_COURSE";
export const LEARNING_GET_ALL_COURSES = "LEARNING_GET_ALL_COURSES";
export const LEARNING_SET_CURRENT_COURSE_DATA = "LEARNING_SET_CURRENT_COURSE_DATA";
export const LEARNING_GET_CURRENT_COURSE_DATA = "LEARNING_GET_CURRENT_COURSE_DATA";

export const LEARNING_GET_CATEGORIES = "LEARNING_GET_CATEGORIES";
export const LEARNING_SET_CATEGORIES = "LEARNING_SET_CATEGORIES";
export const LEARNING_GET_TIMES = "LEARNING_GET_TIMES";
export const LEARNING_SET_TIMES = "LEARNING_SET_TIMES";
export const LEARNING_GET_LEVELS = "LEARNING_GET_LEVELS";
export const LEARNING_SET_LEVELS = "LEARNING_SET_LEVELS";
export const LEARNING_GET_LANGS = "LEARNING_GET_LANGS";
export const LEARNING_SET_LANGS = "LEARNING_SET_LANGS";

export const LEARNING_SAVE = "LEARNING_SAVE";

export const LEARNING_LECTURE_VIDEO_SAVE = "LEARNING_LECTURE_VIDEO_SAVE";
export const LEARNING_LECTURE_RESOURCE_ADD = "LEARNING_LECTURE_RESOURCE_ADD";
export const LEARNING_LECTURE_RESOURCE_REMOVE = "LEARNING_LECTURE_RESOURCE_REMOVE";
export const LEARNING_LECTURE_DESCRIPTION_SAVE = "LEARNING_LECTURE_DESCRIPTION_SAVE";
// export const LEARNING_CHANGE_ORDER_AFTER_DRAG = "LEARNING_CHANGE_ORDER_AFTER_DRAG";

export const LEARNING_CREATE_COURSE_FILL_PLAN_FIELD = "LEARNING_CREATE_COURSE_FILL_PLAN_FIELD";
export const LEARNING_SET_ACTIVE_PLAN_ID = "LEARNING_SET_ACTIVE_PLAN_ID";
export const LEARNING_ADD_CHAPTER_TO_PLAN = "LEARNING_ADD_CHAPTER_TO_PLAN";
export const LEARNING_LECTURE_REMOVE_FILLER = "LEARNING_LECTURE_REMOVE_FILLER";
export const LEARNING_ADD_LECTURE_TO_CHAPTER = "LEARNING_ADD_LECTURE_TO_CHAPTER";

export const LEARNING_ADD_TEST_TO_CHAPTER = "LEARNING_ADD_TEST_TO_CHAPTER";
export const LEARNING_ADD_QUESTION_TO_TEST = "LEARNING_ADD_QUESTION_TO_TEST";
export const LEARNING_REMOVE_QUESTION_FROM_TEST = "LEARNING_REMOVE_QUESTION_FROM_TEST";
export const LEARNING_SAVE_QUESTION_TO_TEST = "LEARNING_SAVE_QUESTION_TO_TEST";

export const LEARNING_SET_CORRECT_ANSWER = "LEARNING_SET_CORRECT_ANSWER";
export const LEARNING_SAVE_QUESTION = "LEARNING_SAVE_QUESTION";
export const LEARNING_REMOVE_ANSWER = "LEARNING_REMOVE_ANSWER";

export const LEARNING_SET_ALL_COURSE_DATA = "LEARNING_SET_ALL_COURSE_DATA";
